components/ContactMethod/contactMethod.component.html, components/home-tab.html, components/phone-input.component.html, components/phone-input.component.ts
=> New component to simplify phone inputs. See how it works in

components/home-tab.html
Changed first image to music star/person wearing apron picture.
=> DEF132 Updated Home screen Images

components/app-header.component.html, components/app-header.component.scss, components/home-tab.html
=> Defect Fixes

components/ContactMethod/contactMethod.component.html, components/ContactMethod/contactMethod.component.ts, components/phone-input.component.html, components/phone-input.component.ts
Phone number inputs are now in one field, instead of three. As numbers are entered, the field will auto format the number like (123) 456-7890.
Note: there are corresponding changes to sacpcp as well.
=> Phone number formatting and validation

components/accordion-box.ts, model/myEvent.ts, model/volunteer-event.ts, pipe/eventsortpipe.ts
removed unused imports/variables/function definitions
=> [linting] removed unused imports/variables

components/ContactMethod/contactMethod.component.ts, components/phone-input.component.ts
They have been unbroken, and the way they work can best be sampled on the MyProfile and Registration pages respectively.
=> PhoneInput and ContactMethod repaired

components/privacy-terms-content.html, components/privacy-terms-content.scss
commit a5bad19c966defb89b4a9d9f649ec0fb2d2e5465
Author: thangthin <thangthin@gmail.com>
Date:   Sun May 7 23:39:38 2017 -0500
[def-230] fixed typo Optiong-out to Option-out
commit e38a4b77a713dcb1dd1874ac4ba7220e6b160e12
Author: thangthin <thangthin@gmail.com>
Date:   Sun May 7 23:34:41 2017 -0500
[def-230]added css class pt-secondary-header to add specifity to fix privacy term in modal view
=> Squashed commit of the following:

components/ContactMethod/contactMethod.component.html, components/phone-input.component.html
Fix for Def 181 in time for UF launch :100:
=> Def 181 - Reorganizing the Contact Method

model/organization.ts, provider/config.ts, service/organization.ts
added organization_id and status to organization, added MY_PENDING_ORGANIZATIONS_URI and call to get pending organizations to show under MyGroups
=> added organization_id and status to organization, added MY_PENDING_ORGANIZATIONS_URI and call to get pending organizations to show under MyGroups

provider/config.ts, service/organization.ts
=> US 9.6 added new method to PUT status 2 on pending org so that it moves to approved immediately

model/contact.ts, model/member.ts, service/volunteer-events-service.ts
Changed Contact.ts and Member.ts to support group-event attendees; changed volunteer-events-service to fix a problem with making changes to profile.
=> [SAVI-LIB 20180219] add attendee merge.

provider/config.ts, service/organization.ts
Added constants for getting organizatio types
Orgnanization get_options modified to get key from user id, from user services.
Added get organization types
=> 	modified:   provider/config.ts

service/organization.ts
Added methods to update Organization Requests and Organization Contacts.
US 9.5
=> Added putOrganization Request and putOrgContactRequest methods

model/myOrgEvents.ts, service/organization.ts
Updated services for Group Event Signup.
=> US 9.8 9.9

components/privacy-terms-content.html
[DEF 428] replace all occurrences of website with application/website in privacy and terms
=> [DEF 428] replace all occurrences of website with application/website in privacy and terms

components/member-data-entry/member-data-entry.html, model/organization.ts, service/organization.ts
due to Groups support.  Also has a change to some error placeholder text for member-data-entry.html
=> service and model changes to organization

components/home-tab.html, components/home-tab.scss, provider/config.ts, service/organization.ts
Also added scss for customizing home page slide show (red/gray dots).  Added explicit option setting for slide show in hope that it fixes Note 3 defect
=> Updated organizations service to support account/organization put

components/home-tab.scss, components/member-data-entry/member-data-entry.html, components/member-data-entry/member-data-entry.ts, components/phone-input-reactive.html, components/phone-input-reactive.scss, components/phone-input-reactive.ts
Added support for phone masking by copying PhoneInput to PhoneInputReactive and then adding reactive form validation.  Updated formatting error messages.
=> Updated MemberDataEntry and added PhoneInputReactive

service/volunteer-events-service.ts
side caching.  Added group cancel to the event details page.
=> Performance/201811 - Category Caching, fixed event api calls to match up for better server

components/app-header.component.html, components/app-header.component.ts
All functionality is in place.  Team is still working on final svg image.
=> Add Donate Heart on NavBar
